# Phase 2: Feature Engineering

## IIT Kharagpur Fugacity ML Hackathon

### Objective

The objective of this notebook is to create meaningful engineered features that improve prediction accuracy.

The feature engineering process is guided by:

- Exploratory Data Analysis
- Chemical Engineering Principles
- Competition Problem Statement
- Machine Learning Best Practices

Only features that improve cross-validation RMSE will be retained.

In [1]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

from sklearn.ensemble import RandomForestRegressor

In [2]:
train = pd.read_csv("../data/raw/train_dataset.csv")
test = pd.read_csv("../data/raw/test_dataset.csv")

print(train.shape)
print(test.shape)

(150, 6)
(50, 5)

In [4]:
X = train.drop(columns=["overall_yield"]).copy()

y = train["overall_yield"]

X_test = test.copy()

In [5]:
X["temp_difference"] = (
    train["jacket_temperature_K"]
    -
    train["inlet_temperature_K"]
)

X_test["temp_difference"] = (
    test["jacket_temperature_K"]
    -
    test["inlet_temperature_K"]
)

In [8]:
X["temp_ratio"] = (
    train["jacket_temperature_K"]
    /
    train["inlet_temperature_K"]
)

X_test["temp_ratio"] = (
    test["jacket_temperature_K"]
    /
    test["inlet_temperature_K"]
)

In [9]:
X["residence_time_proxy"] = (
    train["length_m"]
    /
    train["flow_rate_L_min"]
)

X_test["residence_time_proxy"] = (
    test["length_m"]
    /
    test["flow_rate_L_min"]
)

In [10]:
X["flow_length"] = (
    train["flow_rate_L_min"]
    *
    train["length_m"]
)

X_test["flow_length"] = (
    test["flow_rate_L_min"]
    *
    test["length_m"]
)

In [11]:
X["conc_temp"] = (
    train["concentration_mol_L"]
    *
    train["inlet_temperature_K"]
)

X_test["conc_temp"] = (
    test["concentration_mol_L"]
    *
    test["inlet_temperature_K"]
)

In [12]:
X["flow_temp"] = (
    train["flow_rate_L_min"]
    *
    train["inlet_temperature_K"]
)

X_test["flow_temp"] = (
    test["flow_rate_L_min"]
    *
    test["inlet_temperature_K"]
)

In [13]:
X["temp_severity"] = (
    train["jacket_temperature_K"]
    *
    train["concentration_mol_L"]
)

X_test["temp_severity"] = (
    test["jacket_temperature_K"]
    *
    test["concentration_mol_L"]
)

In [14]:
X.head()

,flow_rate_L_min,concentration_mol_L,inlet_temperature_K,length_m,jacket_temperature_K,temp_difference,temp_ratio,residence_time_proxy,flow_length,conc_temp,flow_temp,temp_severity
0,33.09,3.68,357.75,19.87,383.79,26.04,1.072788,0.600484,657.4983,1316.5200,11837.9475,1412.3472
1,76.30,1.34,429.70,14.84,405.72,-23.98,0.944194,0.194495,1132.2920,575.7980,32786.1100,543.6648
2,59.90,1.01,431.10,11.76,385.40,-45.70,0.893992,0.196327,704.4240,435.4110,25822.8900,389.2540
3,49.90,2.21,445.61,22.85,367.74,-77.87,0.825251,0.457916,1140.2150,984.7981,22235.9390,812.7054
4,16.70,3.95,458.91,4.56,374.13,-84.78,0.815258,0.273054,76.1520,1812.6945,7663.7970,1477.8135

In [15]:
X.describe()

,flow_rate_L_min,concentration_mol_L,inlet_temperature_K,length_m,jacket_temperature_K,temp_difference,temp_ratio,residence_time_proxy,flow_length,conc_temp,flow_temp,temp_severity
count,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000
mean,40.466800,2.311333,424.423400,14.086533,442.240800,17.817400,1.053826,0.567448,566.601294,979.299791,17038.839409,1025.425239
std,22.239772,1.019844,45.200641,6.995343,55.047768,70.602622,0.172390,0.620900,444.521380,443.898705,9272.322635,474.041765
min,5.410000,0.520000,351.630000,2.260000,354.010000,-128.050000,0.740999,0.035513,21.153600,220.616000,1970.159700,199.025600
25%,21.112500,1.362500,387.255000,8.027500,393.327500,-35.707500,0.916494,0.191077,201.606050,577.003200,8993.473750,601.247500
50%,38.610000,2.445000,425.630000,14.235000,437.080000,14.850000,1.040992,0.347751,429.813200,1003.937650,15775.163050,1068.723400
75%,61.227500,3.155000,462.972500,20.685000,486.180000,71.937500,1.175314,0.694635,873.610200,1309.677975,24936.401550,1412.356350
max,79.020000,3.970000,498.580000,24.990000,547.990000,176.620000,1.500723,4.493530,1640.232000,1955.264700,36811.250700,1968.881800

In [16]:
X.shape

(150, 12)

In [17]:
engineered_train = X.copy()
engineered_train["overall_yield"] = y

engineered_train.to_csv(
    "../data/processed/train_engineered.csv",
    index=False
)

X_test.to_csv(
    "../data/processed/test_engineered.csv",
    index=False
)